### ISSUE TITLE
register_topics version too strict?

### ISSUE THREAD

**Issue by rhytnen** [AllenInstitute/pigeon#6]
`def register_topics(self, topics: Dict[str, Callable], version: str):`

This seems to require all topics to be at the same version.  I may misunderstand the intention of versioning but at first glance, it doesn't appear that this is what you actually mean to do.  Shouldn't messages independently be able to change without republishing the entire set of messages?

An additional observation that isn't a bug is that I think register_topics() should iteratively call register_topic().  It's hard to imagine a set of messages so large the performance gain from calling update matters.

From an abstract point of view, the responsibility with managing what it means to register a topic should reside in one place so that if the logic changes, you are not responsible for changing that logic in multiple places.

**Comment by CameronDevine** [comment]
I can certainly modify `register_topics()` to iteratively call `register_topic()`.

The reason I am specifying a single version per call to `register_topics()` is because of the automatic message loading scheme I created. Python packages can be created with an entry-point which contains a mapping from topics to message definitions, and the Python package version. For example:

https://github.com/AllenInstitute/TEM_comms/blob/master/TEM_comms/__init__.py
